let myAge = 38;
let myName = 'Jason Hardman';
console.log(`My name is ${myName} and I'm ${myAge} years old.`);
console.log('So, at age ' + myAge + ', I\'m feeling my age more and more.');
let deathDate = 'unknown';
console.log(deathDate);
let label = ' years old';
console.log(typeof myAge);
console.log(typeof label);
let ageWithLabel = myAge + label;
console.log(typeof ageWithLabel);
